package main

import (
	"fmt"
	"strings"
)

const generatedNotice = "// Code generated by go run ./tools/buildnpm; DO NOT EDIT.\n"

type sourceWriter struct {
	strings.Builder
}

func (w *sourceWriter) line(format string, arguments ...any) {
	fmt.Fprintf(&w.Builder, format+"\n", arguments...)
}

func generatedFiles() map[string]string {
	files := map[string]string{
		"runtime.js": generateRuntime(),
		"index.js": generateModuleEntry("./runtime.js", "core", "",
			"localize", "createLocalizer", "DataLocalizerError", "ConfigurationError", "MissingTranslationError", "CycleError"),
		"adapters/framework.js": generateModuleEntry("../runtime.js", "framework", "", "createRequestLocalizer", "getAcceptLanguage"),
		"adapters/express.js":   generateModuleEntry("../runtime.js", "express", "default", "expressLocalizer", "default"),
		"adapters/nest.js":      generateModuleEntry("../runtime.js", "nest", "", "NestDataLocalizer", "DataLocalizerInterceptor", "createNestInterceptor"),
		"adapters/fastify.js":   generateModuleEntry("../runtime.js", "fastify", "default", "fastifyLocalizer", "default"),
		"adapters/koa.js":       generateModuleEntry("../runtime.js", "koa", "default", "koaLocalizer", "default"),
	}
	for name, declaration := range declarationFiles() {
		files[name] = declaration
	}
	return files
}

func generateRuntime() string {
	var output sourceWriter
	output.WriteString(generatedNotice)
	output.line(`"use strict";`)
	output.line("")
	output.line(`const fs = require("node:fs");`)
	output.line(`const path = require("node:path");`)
	output.line(`const { webcrypto } = require("node:crypto");`)
	output.line("")
	output.line(`if (!globalThis.crypto) globalThis.crypto = webcrypto;`)
	output.line(`require("./wasm_exec.js");`)
	output.line("")
	output.line(`const wrappers = new WeakMap();`)
	output.line(`function wrap(value) {`)
	output.line(`  if (value instanceof Error) throw value;`)
	output.line(`  if (value instanceof Promise) return value;`)
	output.line(`  if ((typeof value !== "function" && typeof value !== "object") || value === null) return value;`)
	output.line(`  if (typeof value === "function" && value.prototype instanceof Error) return value;`)
	output.line(`  if (wrappers.has(value)) return wrappers.get(value);`)
	output.line(`  let wrapped;`)
	output.line(`  if (typeof value === "function") {`)
	output.line(`    wrapped = function (...args) { return wrap(Reflect.apply(value, this, args)); };`)
	output.line(`    if (value.prototype) wrapped.prototype = value.prototype;`)
	output.line(`  } else {`)
	output.line(`    wrapped = Array.isArray(value) ? [] : Object.create(Object.getPrototypeOf(value));`)
	output.line(`    wrappers.set(value, wrapped);`)
	output.line(`    for (const key of Reflect.ownKeys(value)) {`)
	output.line(`      const descriptor = Object.getOwnPropertyDescriptor(value, key);`)
	output.line(`      if (Object.hasOwn(descriptor, "value")) descriptor.value = wrap(descriptor.value);`)
	output.line(`      Object.defineProperty(wrapped, key, descriptor);`)
	output.line(`    }`)
	output.line(`    if (Object.isFrozen(value)) Object.freeze(wrapped);`)
	output.line(`    return wrapped;`)
	output.line(`  }`)
	output.line(`  wrappers.set(value, wrapped);`)
	output.line(`  return wrapped;`)
	output.line(`}`)
	output.line("")
	output.line(`globalThis.__dataLocalizerRequire = require;`)
	output.line(`globalThis.__dataLocalizerWrap = wrap;`)
	output.line(`const go = new globalThis.Go();`)
	output.line(`const wasmPath = path.join(__dirname, "data-localizer.wasm");`)
	output.line(`const moduleInstance = new WebAssembly.Module(fs.readFileSync(wasmPath));`)
	output.line(`const instance = new WebAssembly.Instance(moduleInstance, go.importObject);`)
	output.line(`void go.run(instance);`)
	output.line(`if (!globalThis.__dataLocalizerModules) throw new Error("the Go WebAssembly runtime did not initialize");`)
	output.line(`module.exports = wrap(globalThis.__dataLocalizerModules);`)
	return output.String()
}

func generateModuleEntry(runtimePath, moduleName, defaultExport string, exports ...string) string {
	var output sourceWriter
	output.WriteString(generatedNotice)
	output.line(`"use strict";`)
	output.line("")
	output.line(`const api = require(%q).%s;`, runtimePath, moduleName)
	if defaultExport != "" {
		output.line(`module.exports = api.%s;`, defaultExport)
	}
	for _, name := range exports {
		output.line(`module.exports.%s = api.%s;`, name, name)
	}
	return output.String()
}
