name: Sequential CI/CD Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  release:
    needs: check
    uses: ./.github/workflows/release.yml
    secrets: inherit
