name: Sequential CI/CD Pipeline

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: check
    permissions:
      contents: write
    uses: ./.github/workflows/release.yml
    secrets: inherit
